### ISSUE TITLE
Problem with year extraction when exact date is given

### ISSUE THREAD

**Issue by lehkost** [dracor-org/rdracor#12]
According to the README, GerDraCor has this date range for premieres:
```
Premiere years (range): 1650 - 1981
```
Yet it shouldn't start at 1560, but at 1549, since [this play](https://dracor.org/id/ger000597) premiered earlier. It seems to be a problem with year extraction. Some plays use the exact day for time codes (especially premieres). In said play it says (see the passage [in TEI](https://github.com/dracor-org/gerdracor/blob/main/tei/sachs-ein-comedi-von-dem-reichen-sterbenden-menschen-der-hecastus-genannt.xml#L140)):
```xml
<event type="written" when="1549-09-06">
  <desc/>
</event>
```
Not sure where the extraction happens, on API level or in rdracor directly. Could it be fixed? Or should we revert all exact days to years only in TEI files?

**Comment by cmil** [comment]
@lehkost The earliest `premiereYear` recorded in GerDraCor is indeed 1650: https://dracor.org/id/ger000550. The Hecastus was _written_ in 1549, which is earlier, but it is not the year of the premiere which seems to be unknown, at least in GerDraCor.

**Comment by lehkost** [comment]
Sorry, my bad, I meant this output instead:
```
Written years (range): 1646 - 1947
```
This should start in 1549, no?

**Comment by cmil** [comment]
Maybe the problem then is indeed that the DraCor API issues the full date as given in the `when` attribute in a property that is called `writtenYear` which is a bit misleading. Maybe we should either rename it to `dateWritten` or really just issue the year as a number. I also noticed that we use `writtenYear`, `premiereYear` etc. in the list of plays in `/corpora/{corpusname}` but in the meta data for a single play (e.g. https://dracor.org/api/corpora/ger/play/sachs-ein-comedi-von-dem-reichen-sterbenden-menschen-der-hecastus-genannt) we use `yearWritten`, `yearPremiered` etc. This should probably be harmonised too.

**Comment by lehkost** [comment]
Would it be possible to extract only the year from the TEI files even if a full date is given?

And I'm all for harmonisation of denominators of our extracted data, I'd prefer 'year' as prefix, i.e. yearWritten, yearPremiere, yearPrinted, yearNormalized, what do you think?

**Comment by cmil** [comment]
@lehkost yes, I created a ticket. ☝️

**Comment by lehkost** [comment]
great, thanks! that was my favourite option as well :)

**Comment by Pozdniakov** [comment]
So, should I change something for now? maybe include parse dates like "1549-09-06"?

**Comment by lehkost** [comment]
No, see above, this will be solved on the API level, nothing to change for the rdracor package. 😊
