### ISSUE TITLE
"figure margins too large" with plot(corpora)

### ISSUE THREAD

**Issue by lehkost** [dracor-org/rdracor#16]
Not sure if this is reproducible for others, but at the moment ```plot(corpora)``` throws an error (it did work before, though):
```
Fehler in plot.new() : figure margins too large
Fehler in par(oldpar) : 
  ungültiger Wert für den Grafikparameter "pin" spezifiziert
Zusätzlich: Warnmeldung:
In par(oldpar) : par(new) ohne Plot aufgerufen
```
I was following the codelines in the README.

**Comment by Pozdniakov** [comment]
Usually this happens when your tab in RStudio is too small:

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/18327620/220658710-c3c70768-3d67-4315-8925-4922eefed656.png">

It is not related to {rdracor}, it is a global R/RStudio problem.
