### ISSUE TITLE
Changes in the API structure 

### ISSUE THREAD

**Issue by KovaZo** [dracor-org/rdracor#25]
Hello :) 
Thank you very much for providing this helpful package :) 

I tested the package yesterday and except the "get_dracor_meta" function, I received an error message for the other functions (test: "get_dracor", "get_play_metadata", and "get_net_cooccur_igraph").
The reasons for the errors seem to be changes to the endpoints of the API and the internal structure of the responses.
If I made a "mistake" using the package, let me know - I followed the README file.

I have forked the package and changed the code to work in my case. If that helps, feel free to take a look. 
If you have any more questions, let me know :)

Best regards,
KovaZo

**Comment by Pozdniakov** [comment]
Hi, KovaZo!

Thanks a lot for your fix. Unfortunately, I found it out after I updated rdracor to the new API, so, we did double work :) However, I compared our commits and applied lots of your modifications where it was better than mine. You can see them in 1.0.1 version.

So, thanks a lot, it was indeed helpful!

Best,
Ivan
