### ISSUE TITLE
Switch Travis and Codecov to a dracor-org setup

### ISSUE THREAD

**Issue by cmil** [dracor-org/rdracor#4]
Currently the Travis and Codecov badges in the README point to the fork https://github.com/Pozdniakov/rdracor. This should be changed to reflect the status of the [dracor-org](/dracor-org/rdracor) repo.

**Comment by Pozdniakov** [comment]
as for now deleted that, maybe I'll return it later. Travis is a bit overkill and doesn't fit well the workflow, Codecov will be good if I cover all code lines)
