### ISSUE TITLE
couldn't install package

### ISSUE THREAD

**Issue by silviaegt** [dracor-org/rdracor#6]
Dear @Pozdniakov and @lehkost, 
thank you for this amazing tool, I'm really looking forward to play with it! However I tried:

`devtools::install_github("dracor-org/rdracor")
`

And got:
```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`dracor-org`) and repo name (`rdracor`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

Do I need special permissions to access the repo?

**Comment by lehkost** [comment]
Hi Silvia! I just tried, it works for me in RStudio.

For the time being, maybe try the current dev version [here on Vanya's repo](https://github.com/Pozdniakov/rdracor), including installation guide.

**Comment by cmil** [comment]
@silviaegt does this work for you:

```
devtools::install_github("dracor-org/rdracor", ref = "main")
```

The default branches in dracor-org repos are named `main` not `master`.

**Comment by silviaegt** [comment]
Yay! That worked, thanks for the hint @cmil!
